version: "3"
services:
    tomcat:
        build: ./tomcat
        image: shabliad/tomcat
        restart: unless-stopped
        ports:
            - "8080:8080"
            - "8443:8443"
        volumes:
            - ./tomcat/logs:/usr/local/tomcat/logs
            - ./tomcat/opts:/usr/local/tomcat/opts
        environment:
            JAVA_OPTS: -Xms256m -Xmx1024m -XX:+UseParallelOldGC -XX:MaxPermSize=384m -Dservice.configurationFile=/usr/local/tomcat/service.properties
        entrypoint: ./scripts/wait-for-it.sh -t 60 mysql:3306 -- ./scripts/wait-for-it.sh -t 60 ldap:389 -- ./scripts/tomcat.sh
        depends_on:
            - mysql
            - ldap
			- wiremock

    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/sql_scripts:/docker-entrypoint-initdb.d

    wiremock:
        image: holomekc/wiremock-gui:latest
        command:
            java -XX:+PrintFlagsFinal $JAVA_OPTIONS -jar /home/wiremock/wiremock.jar --global-response-templating --port 9090
        ports:
            - "9090:9090"

    ldap:
        image: openidentityplatform/opendj:latest
        user: root
        environment:
            ROOT_PASSWORD: password
            BASE_DN: dc=sample,dc=com
            PORT: 389
            LDAPS_PORT: 636
        volumes:
          - ./ldap:/opt/opendj/bootstrap/schema/
        ports:
            - "389:389"
            - "636:636"
            - "4444:4444"