version: "3"
services:
    tomcat:
        build: ./tomcat
        image: shabliad/tomcat:latest
        ports:
            - "8080:8080"
        volumes:
            - ./tomcat/logs:/usr/local/tomcat/logs
        depends_on:
            - mysql
    
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/sql_scripts:/docker-entrypoint-initdb.d